apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-hr  # 统一命名
spec:
  selector:
    matchLabels:
      app: smart-hr
  template:
    metadata:
      labels:
        app: smart-hr
    spec:
      containers:
      - name: smart-hr
        image: paas-tob-dev-cn-beijing.cr.volces.com/hiagent-app/smart-hr:0.1  # 镜像名称直接写在此处
        imagePullPolicy: Always  # 添加镜像拉取策略
        ports:
        - containerPort: 80
        resources:
          requests:  # 新增资源请求配置
            memory: "150Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:  
      - name: volc-secret  # 通过secret名称引用密码

---
apiVersion: v1
kind: Service
metadata:
  name: smart-hr-service
spec:
  type: LoadBalancer  # 直接使用负载均衡器暴露服务
  selector:
    app: smart-hr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# 移除Ingress配置部分
